name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
      - 'v*'

env:
  NODE_VERSION: 20
  YARN_VERSION: 1.22.21

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install Yarn
        run: |
          npm install -g yarn@${{ env.YARN_VERSION }}
          yarn --version

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    environment: npm-publish
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_ORG: ${{ secrets.NPM_ORG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Verify version format
        run: |
          if [[ ! $GITHUB_REF =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version format: $GITHUB_REF. Must be vX.Y.Z"
            exit 1
          fi
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install Yarn
        run: |
          npm install -g yarn@${{ env.YARN_VERSION }}
          yarn --version

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup .npmrc for publishing
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          echo "@$NPM_ORG:registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc

      - name: Build project
        run: yarn build

      - name: Publish to npm
        run: npm publish